### ISSUE TITLE
프로젝트 시작

### ISSUE THREAD

**Issue by qpfmtlcp** [qpfmtlcp/django-board-practice#1]
1. 프로젝트 생성
2. 앱 생성
3. 기본 CRUD API 생성
```
model {
  title
  contents
  created
  modified
}
```

**Comment by siransfe** [comment]
이홍채

**Comment by qpfmtlcp** [comment]
@siransfe 참고 링크
https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/

**Comment by qpfmtlcp** [comment]
@siransfe 모델 생성할 때 참조
https://django-model-utils.readthedocs.io/en/latest/index.html

generic view 사용

**Comment by qpfmtlcp** [comment]
4. 의존성 패키지 정리
https://2siwon.github.io/pip/2017/09/25/pip-002-pip-freeze.html
